name: Deploy Fame website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.GT_KEY }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/owner/fame-gta5.com
            git pull --recurse-submodules origin master --rebase
            docker-compose down fame_frontend fame_backend nginx
            docker-compose up fame_frontend fame_backend --build -d
            docker-compose up nginx -d
